"""add stock_count to products

Revision ID: 1ad5c4e62185
Revises: dd92cfa3fb59
Create Date: 2026-07-07 19:47:47.229659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad5c4e62185'
down_revision: Union[str, Sequence[str], None] = 'dd92cfa3fb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "products",
        sa.Column(
            "stock_count",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock_count')
    # ### end Alembic commands ###
