"""create product categories

Revision ID: 76a86b060918
Revises: b7c9e2a41d6f
Create Date: 2026-07-14 19:22:54.109903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a86b060918'
down_revision: Union[str, Sequence[str], None] = 'b7c9e2a41d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    # ### end Alembic commands ###

    with op.batch_alter_table("products") as batch_op:
        batch_op.add_column(
            sa.Column("category_id", sa.Integer(), nullable=True)
        )
        batch_op.create_index(
            op.f("ix_products_category_id"),
            ["category_id"],
        )
        batch_op.create_foreign_key(
            op.f("fk_products_category_id_categories"),
            "categories",
            ["category_id"],
            ["id"],
        )

    backfill_categories()

    with op.batch_alter_table("products") as batch_op:
        batch_op.alter_column(
            "category_id",
            existing_type=sa.Integer(),
            existing_nullable=True,
            nullable=False,
        )
        batch_op.drop_index(op.f("ix_products_category"))
        batch_op.drop_column("category")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products") as batch_op:
        batch_op.add_column(
            sa.Column("category", sa.String(length=40), nullable=True)
        )

    restore_product_categories()

    with op.batch_alter_table("products") as batch_op:
        batch_op.alter_column(
            "category",
            existing_type=sa.String(length=40),
            existing_nullable=True,
            nullable=False,
        )
        batch_op.drop_constraint(
            op.f("fk_products_category_id_categories"),
            type_="foreignkey",
        )
        batch_op.drop_index(op.f("ix_products_category_id"))
        batch_op.drop_column("category_id")
        batch_op.create_index(
            op.f("ix_products_category"),
            ["category"],
            unique=False,
        )

    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###


products_table = sa.table(
    "products",
    sa.column("category", sa.String),
    sa.column("category_id", sa.Integer),
)
categories_table = sa.table(
    "categories",
    sa.column("id", sa.Integer),
    sa.column("name", sa.String),
    sa.column("slug", sa.String),
)


def slugify_category(name: str) -> str:
    return name.strip().lower().replace(" ", "-")


def backfill_categories() -> None:
    connection = op.get_bind()

    category_names = connection.execute(
        sa.select(products_table.c.category).distinct()
    ).scalars()

    category_ids: dict[str, int] = {}

    for name in sorted(category_names):
        category_id = connection.execute(
            categories_table.insert().values(
                name=name.title(),
                slug=slugify_category(name),
            ).returning(categories_table.c.id)
        ).scalar_one()
        category_ids[name] = category_id

    for name, category_id in category_ids.items():
        connection.execute(
            products_table.update()
            .where(products_table.c.category == name)
            .values(category_id=category_id)
        )


def restore_product_categories() -> None:
    connection = op.get_bind()
    category_slug = (
        sa.select(categories_table.c.slug)
        .where(categories_table.c.id == products_table.c.category_id)
        .scalar_subquery()
    )
    connection.execute(
        products_table.update().values(category=category_slug)
    )
